# https://iniox.github.io/#matugen/configuration
[config.wallpaper]
command = "swww"
set = false

[templates.vicinae]
input_path = './templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
post_hook = 'vicinae theme set matugen'

[templates.hyprland]
input_path = './templates/hyprland.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

# [templates.kitty]
# input_path = './templates/kitty.conf'
# # output_path = '~/.config/kitty/matugen.conf'
# output_path = '~/.config/kitty/themes/matugen.conf'
# post_hook = "kitty +kitten themes --reload-in=all matugen"

[templates.gtk3]
input_path = './templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = './templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

# [templates.tmux]
# input_path = './templates/tmux.conf'
# output_path = '~/.config/tmux/matugen.conf'
# post_hook = 'tmux source-file ~/.config/tmux/matugen.conf' 
